class ZCL_ABS_ABAP_MAINTAIN definition
  public
  final
  create public .

public section.

  constants C_MSGTY_ERROR type CHAR1 value 'E' ##NO_TEXT.
  constants C_MSGTY_INFO type CHAR1 value 'I' ##NO_TEXT.
  constants C_OBJ_TYP_ORDER type J_OBART value 'OR' ##NO_TEXT.
  constants C_OBJ_TYP_ASSET type J_OBART value 'AN' ##NO_TEXT.
  constants C_OBJ_TYP_COST_CENTER type J_OBART value 'KS' ##NO_TEXT.
  constants C_AGRI_NAME_SPACE type CHAR6 value '/AGRI/' ##NO_TEXT.
  constants C_REQUIREMENT_TYP_AR type J_OBTYP value 'AR' ##NO_TEXT.
  constants C_OBJECT_TYP_PP_PM type J_OBTYP value 'OKP' ##NO_TEXT.
  constants C_INSERT type UPDKZ value 'I' ##NO_TEXT.
  constants C_UPDKZ_INSERT type UPDKZ value 'I' ##NO_TEXT.
  constants C_INDICATOR_CREDIT type SHKZG value 'H' ##NO_TEXT.
  constants C_MOMENT_TYP_GI_ORDER type BWART value '261' ##NO_TEXT.
  constants C_MOVEMENT_TYP_GI_ORDER type BWART value '261' ##NO_TEXT.
  constants C_ITEM_CAT_STOCK type POSTP value 'L' ##NO_TEXT.
  constants C_COSTING_REL_FULL type CK_SELKZ value 'X' ##NO_TEXT.
  constants C_ACTIVITY_NUM_INITIAL type VORNR value '10' ##NO_TEXT.
  constants C_DISTRIBUTE_FUN_DISP_SDATE type CY_FUNCT value 'S10' ##NO_TEXT.
  constants C_OBJ_TYP_MATERIAL type J_OBART value 'MA' ##NO_TEXT.
  constants C_OBJ_TYP_WBS_ELEMENT type J_OBART value 'PR' ##NO_TEXT.
  constants C_OBJ_TYP_GL_ACCOUNT type J_OBART value 'SK' ##NO_TEXT.
  constants C_OBJ_TYP_SALES_DOC type J_OBART value 'VB' ##NO_TEXT.
  constants C_HIERARCHY_NO_50 type BRGHIENR value '050' ##NO_TEXT.
  constants C_SETTLE_TYP_PERIODIC type PERBZ_LD value 'PER' ##NO_TEXT.
  constants C_SETTLE_TRANS_ACTUAL type AVORG value 'KOAO' ##NO_TEXT.
  constants C_STAUS type J_STATUS value 'I0028' ##NO_TEXT.
  constants C_CUS_VARHDR_TAB type DD02L-TABNAME value 'ZABST_VTCHDR' ##NO_TEXT.
  constants C_CUS_VARITM_TAB type DD02L-TABNAME value 'ZABST_VTCITM' ##NO_TEXT.
  constants C_VARHDR_TAB type DD02L-TABNAME value 'ZABST_VTHDR' ##NO_TEXT.
  constants C_OBJECT_LOG type BALOBJ-OBJECT value '/AGRI/GMBK' ##NO_TEXT.
  constants C_OPTN_GRE_THN type /AGRI/GM_OPTION value 'GT' ##NO_TEXT.
  constants C_VARITM_TAB type DD02L-TABNAME value 'ZABST_VTITM' ##NO_TEXT.
  constants C_CHARACT_PSDAT type ATNAM value 'ZLOBM_HSDAT' ##NO_TEXT.
  constants C_UCOMM_BATCH_CONF type SY-UCOMM value 'BCNF' ##NO_TEXT.
  constants C_BATCH_DETAILS type SY-UCOMM value 'DTLS' ##NO_TEXT.
  constants C_MVT_IND_PROD_ORDER type KZBEW value 'F' ##NO_TEXT.
  constants C_GM_CODE_CONSUMPTION type GM_CODE value '02' ##NO_TEXT.
  constants C_MOVE_TYPE_PO_REVERSAL type BWART value '102' ##NO_TEXT.
  constants C_MOVE_TYPE_BATCH_DISC type BWART value 'Y91' ##NO_TEXT.
  constants C_FCODE_BTCH_DISCARD type CHAR5 value 'BDIS' ##NO_TEXT.
  constants C_OBJID_NURSERY_WB type ZABS_DEL_OBJID value 'NSWB' ##NO_TEXT.
*  constants C_K1VAL type CHAR4 value 'BNOR' ##NO_TEXT.
  constants C_KEY_BATCH_NR type CHAR4 value 'BNOR' ##NO_TEXT.
  constants C_OBJ_BTCH_NR type INRI-OBJECT value 'ZABS_BATCH' ##NO_TEXT.
  constants C_MODE_DISPLAY type CHAR1 value 'A' ##NO_TEXT.
  constants C_ORDLVL_PROCESS type /AGRI/GLORDLV value 'A' ##NO_TEXT.
  constants C_ORDLVL_TASK_PROCESS type /AGRI/GLORDLV value 'B' ##NO_TEXT.
  constants C_CUST_FIELD_QUANT type LVC_FNAME value 'ZZGWEMG' ##NO_TEXT.
  constants C_USERFN_TASK_ORD type CHAR30 value 'Ordens Tarefa' ##NO_TEXT.
  constants C_USERFN_CHARACT type CHAR30 value 'Características' ##NO_TEXT.
  constants C_MOVE_TYPE_GRN_CREATE type BWART value '101' ##NO_TEXT.
  constants C_DOMNAME_DOC_CAT type DD07L-DOMNAME value '/AGRI/GL_AUTYP' ##NO_TEXT.
  constants C_TO_MONITOR_FCAT type DD02L-TABNAME value 'ZABS_STR_TO_MONITOR_FCAT' ##NO_TEXT.
  constants C_SEL_MODE_CELL type LVC_LIBOX value 'D' ##NO_TEXT.
  constants C_HOLI_CAL_BRAZIL type SCAL-HCALID value 'BR' ##NO_TEXT.
  constants C_FACT_CAL_BRAZIL type SCAL-FCALID value 'BR' ##NO_TEXT.
  constants C_CUST_FIELD_IDENT type LVC_FNAME value 'ZZIDENT' ##NO_TEXT.
  constants C_CUST_FIELD_FORMULA type LVC_FNAME value 'ZZFORMULA' ##NO_TEXT.
  constants C_ATTR_DATATYP_NUM type /AGRI/GATFOR value 'NUM' ##NO_TEXT.
  constants C_ALPHABETS type STRING value 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' ##NO_TEXT.
  constants C_CHAR_DATATYP_CHAR type ATFOR value 'CHAR' ##NO_TEXT.
  constants C_CHAR_DATATYP_CURR type ATFOR value 'CURR' ##NO_TEXT.
  constants C_CHAR_DATATYP_DATE type ATFOR value 'DATE' ##NO_TEXT.
  constants C_USERFN_BATCHES type CHAR30 value 'Lotes' ##NO_TEXT.
  constants C_FCODE_BTCH_DISC type SY-UCOMM value 'BDIS' ##NO_TEXT.
  constants C_FCODE_BTCH_CANC type SY-UCOMM value 'BCAN' ##NO_TEXT.
  constants C_TBL_FIELDS_TABNAME type TABNAME value 'ZABS_STR_GLFLCMACA' ##NO_TEXT.
  constants C_VALFIELD_MDCLASS type DDSHLPDFLD value 'MDCLASS' ##NO_TEXT.
  constants C_VALFIELD_TRCLASS type DDSHLPDFLD value 'TRCLASS' ##NO_TEXT.
  constants C_AGCAT_MP type /AGRI/GLAGCAT value 'MP' ##NO_TEXT.
  constants C_AGCAT_TR type /AGRI/GLAGCAT value 'TR' ##NO_TEXT.
  constants C_VALFIELD_MDATNAM type DDSHLPDFLD value 'MDATNAM' ##NO_TEXT.
  constants C_VALFIELD_TRATNAM type DDSHLPDFLD value 'TRATNAM' ##NO_TEXT.
  constants C_MSRMNT_LEVEL_CS type /AGRI/GLASLVL value 'A' ##NO_TEXT.
  constants C_MSRMNT_LEVEL_TERRAIN type /AGRI/GLASLVL value 'T' ##NO_TEXT.
  constants C_UPDKZ_UPDATE type UPDKZ value 'U' ##NO_TEXT.
  constants C_UPDKZ_DELETE type UPDKZ value 'D' ##NO_TEXT.
  constants C_AGTYP_TERRAIN type /AGRI/GAGTYP value 'X91' ##NO_TEXT.
  constants C_AGTYP_MEASUREMENT_DOC type /AGRI/GAGTYP value 'X90' ##NO_TEXT.
  constants C_CUSTOM_MSG_CLASS type MSGID value 'ZABS_MSGCLS' ##NO_TEXT.
  constants C_UCOMM_ONLI type SYST_UCOMM value 'ONLI' ##NO_TEXT.
  constants C_STR_RES_DISPLAY type DD02L-TABNAME value 'ZABS_STR_RESOURCE_MAINTAIN' ##NO_TEXT.
  constants C_STR_RES_MAINTAIN type DD02L-TABNAME value 'ZABS_STR_RESXLS_MAINTAIN' ##NO_TEXT.
  constants C_RSTYP_EQUIP type /AGRI/FMRSTYPE value 'B' ##NO_TEXT.
  constants C_MSGTY_SUCCESS type CHAR1 value 'S' ##NO_TEXT.
  constants C_ICON_SUCCESS type ZABS_DEL_MSGTYP value '@08@' ##NO_TEXT.
  constants C_ICON_ERROR type ZABS_DEL_MSGTYP value '@0A@' ##NO_TEXT.
  constants C_ICON_WARNING type ZABS_DEL_MSGTYP value '@09@' ##NO_TEXT.
  constants C_CS_FARMING_APPL type /AGRI/GLAB_CLASS value '1' ##NO_TEXT.
  constants C_OUTPUT_DAYS_FORMAT type CHAR2 value '02' ##NO_TEXT.
  constants C_MEAS_DOC_TYPE type ZABS_DEL_OBJID value 'MDTY' ##NO_TEXT.
  constants C_CUSTOM_MODE type ZABS_DEL_MOD value 'C' ##NO_TEXT.
  constants C_STR_ACT_DISPLAY type DD02L-TABNAME value 'ZABS_STR_ACT_MAINTAIN' ##NO_TEXT.
  constants C_TB_FNCODE_CHANGE type UI_FUNC value 'CHANGE' ##NO_TEXT.
  constants C_TB_QUICKINFO type ICONQUICK value 'DISPLAY<->CHANGE' ##NO_TEXT.
  constants C_UCOMM_ENTER type SYUCOMM value 'ENTR' ##NO_TEXT.
  constants C_MODE_CHANGE type CHAR1 value 'V' ##NO_TEXT.
  constants C_UCOMM_SAVE type SYST_UCOMM value 'SAVE' ##NO_TEXT.
  constants C_VARIANT_SAVE type CHAR01 value 'A' ##NO_TEXT.
  constants C_FIELDNAME_UPDKZ type CHAR5 value 'UPDKZ' ##NO_TEXT.
  constants C_FIELDNAME_IDRES type FIELDNAME value 'IDRESOURCE' ##NO_TEXT.
  constants C_FIELDNAME_INTEXT type FIELDNAME value 'INTEXT' ##NO_TEXT.
  constants C_FIELDNAME_HR type FIELDNAME value 'HR' ##NO_TEXT.
  constants C_FIELDNAME_WC type FIELDNAME value 'ARBPL' ##NO_TEXT.
  constants C_LAYOUT_SEL_MODE type LVC_LIBOX value 'A' ##NO_TEXT.
  constants C_LAYOUT_STYLEFNAME type LVC_FNAME value 'STYLE' ##NO_TEXT.
  constants C_POPUP_TB_YES type CHAR3 value 'YES' ##NO_TEXT.
  constants C_POPUP_TB_NO type CHAR2 value 'NO' ##NO_TEXT.
  constants C_BILL_YES type /AGRI/FMBILL value 'YES' ##NO_TEXT.
  constants C_FIELDNAME_IDACTV type FIELDNAME value 'IDACTV' ##NO_TEXT.
  constants C_SPRAS_ENGLISH type SPRAS value 'E' ##NO_TEXT.
  constants C_SPRAS_PORTUGUESE type SPRAS value 'P' ##NO_TEXT.
  constants C_DOC_OBJ_RATIO type I value '95' ##NO_TEXT.
  constants C_CS_APPL type FIELDNAME value 'CLASS' ##NO_TEXT.
  constants C_CS_AF_PLANT_DATE type FIELDNAME value 'ZZFAZPLANTIO' ##NO_TEXT.
  constants C_CS_AF_PLANT_YEAR type FIELDNAME value 'ZZPLANTYEAR' ##NO_TEXT.
  constants C_CS_END_DATE type FIELDNAME value 'DATBI' ##NO_TEXT.
  constants C_CS_AGE_DAYS type FIELDNAME value 'CSAGE' ##NO_TEXT.
  constants C_CS_START_DATE type FIELDNAME value 'DATAB' ##NO_TEXT.
  constants C_CS_AF_AGE_MONTHS type FIELDNAME value 'ZZCSAGE_MONTH' ##NO_TEXT.
  constants C_CS_AF_YEARS_COUNT type FIELDNAME value 'ZZCSYEAR' ##NO_TEXT.
  constants C_CS_AF_AGE_DAYS type FIELDNAME value 'ZZCSAGE' ##NO_TEXT.
  constants C_CS_AF_REPLANTING type FIELDNAME value 'ZZREPLANT' ##NO_TEXT.
  constants C_CS_AF_YMATERIAL type FIELDNAME value 'YMATNR' ##NO_TEXT.
  constants C_CUST_ADD_FIELDTYP type INTTYPE value 'D' ##NO_TEXT.
  constants C_CS_ACTIVE type ASTAT value 'A' ##NO_TEXT.
  constants C_AC_STAT_CONFIRMED type /AGRI/FMASTATUS value 'CNF' ##NO_TEXT.
  constants C_NON_BILLABLE type /AGRI/FMBILL value 'NO' ##NO_TEXT.
  constants C_NUMBERS type STRING value '123456789' ##NO_TEXT.
  constants C_DOMAIN_ACTCG type DD01L-DOMNAME value 'ZABS_DOM_ACTCG' ##NO_TEXT.
  constants C_ACTCG_PROD type ZABS_DEL_ACTCG value 'P' ##NO_TEXT.
  constants C_ACTCG_EVENT type ZABS_DEL_ACTCG value 'E' ##NO_TEXT.
  constants C_OBJID_ACCOMPLISH type ZABS_DEL_OBJID value 'ACCM' ##NO_TEXT.
  constants C_OBJID_MOBILE type ZABS_DEL_OBJID value 'MOBC' ##NO_TEXT.
  constants C_OBJID_MD_STATUS_PROFILE type ZABS_DEL_OBJID value 'STAT' ##NO_TEXT.
  constants C_KEY_COMPLEX type ZABS_DEL_K1VAL value 'COMP' ##NO_TEXT.
  constants C_KEY_EMP_ROLE type ZABS_DEL_K1VAL value 'ROLE' ##NO_TEXT.
  constants C_KEY_LEADER type ZABS_DEL_K1VAL value 'LEAD' ##NO_TEXT.
  constants C_KEY_INCHARGE type ZABS_DEL_K1VAL value 'INCR' ##NO_TEXT.
  constants C_KEY_ACCOMPLISH_CREATE type ZABS_DEL_K1VAL value 'ACRT' ##NO_TEXT.
  constants C_KEY_ACCOMPLISH_TYPE type ZABS_DEL_K1VAL value 'ACTY' ##NO_TEXT.
  constants C_KEY_TASK_MAT_TYPES type ZABS_DEL_K1VAL value 'TMTP' ##NO_TEXT.
  constants C_KEY_MEASUREMENT_ATTR_UPDATE type ZABS_DEL_K1VAL value 'MAUP' ##NO_TEXT.
  constants C_KEY_MEASUREMENT_TYPE type ZABS_DEL_K1VAL value 'MDTP' ##NO_TEXT.
  constants C_ROLE_LEADER type CHAR2 value 'LE' ##NO_TEXT.
  constants C_ROLE_INCHARGE type CHAR2 value 'IN' ##NO_TEXT.
  constants C_PARVW_PERSON type PARVW value 'VW' ##NO_TEXT.
  constants C_TPLVL_FARM type /AGRI/GLTPLVL value '1' ##NO_TEXT.
  constants C_AC_STATUS_CREATED type /AGRI/FMAC_STATUS value 'CTD' ##NO_TEXT.
  constants C_AC_STATUS_CONFIRM type /AGRI/FMAC_STATUS value 'CNF' ##NO_TEXT.
  constants C_OWNERSHIP_OWN type /AGRI/GLOWNSHP value 'OW' ##NO_TEXT.
  constants C_ATTRGRP_CITIMOVEL type /AGRI/GATGRP value 'CIT-IMOVEL' ##NO_TEXT.
  constants C_CHARACT_FAZ_REGIAO type ATNAM value 'FAZ_REGIAO' ##NO_TEXT.
  constants C_MDTYP_ZARV type /AGRI/GLMDTYP value 'ZARV' ##NO_TEXT.
  constants C_CHARACT_ATIVIDADE type ATNAM value 'INV-ATIVIDADE' ##NO_TEXT.
  constants C_CHARACT_CONTAMOTIVO type ATNAM value 'CIT-CONTA-MOTIVO' ##NO_TEXT.
  constants C_CHARACT_QTDADEARV type ATNAM value 'INV-QTDADE-ARV' ##NO_TEXT.
  constants C_CHARVAL_101 type ATWRT value '101' ##NO_TEXT.
  constants C_CHARVAL_102 type ATWRT value '102' ##NO_TEXT.
  constants C_CHARVAL_103 type ATWRT value '103' ##NO_TEXT.
  constants C_CHARVAL_104 type ATWRT value '104' ##NO_TEXT.
  constants C_FILETYP_BINARY type CHAR10 value 'BIN' ##NO_TEXT.
  constants C_FRMNAME_TRNDTLS type FPNAME value 'ZABS_ADBFRM_TERRAIN' ##NO_TEXT.
  constants C_FRMNAME_TRNDTLS_COPY type FPNAME value 'ZABS_ADBFRM_TERRAIN_COPY' ##NO_TEXT.
  constants C_RSIGN_INCLUDE type CHAR1 value 'I' ##NO_TEXT.
  constants C_ROPT_EQUAL type CHAR2 value 'EQ' ##NO_TEXT.
  constants C_STR_MD_MASS_APPROVALS type DD02L-TABNAME value 'ZABS_STR_MD_MASS_APPROVALS' ##NO_TEXT.
  constants C_STR_GLMD_CONTEXT type BALTABNAME value 'ZABS_STR_GLMD_CONTEXT' ##NO_TEXT.
  constants C_ROLE_LOADER type CHAR2 value 'LD' ##NO_TEXT.
  constants C_ROLE_BIN type CHAR2 value 'BN' ##NO_TEXT.
  constants C_ATGRP_FRUTA_MP type /AGRI/GATGRP value 'Z_FRUTA_MP' ##NO_TEXT.
  constants C_IRR_MONITOR_FCAT type DD02L-TABNAME value 'ZABS_STR_IRR_MONITOR_FCAT' ##NO_TEXT.
  constants C_IRRTYP type /AGRI/FMIRTYP value '001' ##NO_TEXT.
  constants C_RSIGN_EXCLUDE type CHAR1 value 'E' ##NO_TEXT.
  constants C_OBJ_ORD_NR type INRI-OBJECT value 'ZABS_ORDER' ##NO_TEXT.
  constants C_AUTYP_PRO_ORD type /AGRI/GL_AUTYP value 'AO' ##NO_TEXT.
  constants C_AUTYP_TSK_ORD type /AGRI/GL_AUTYP value 'TO' ##NO_TEXT.
  constants C_NEW type CHAR3 value 'NEW' ##NO_TEXT.
  constants C_OBJID_IRR_WB type ZABS_DEL_OBJID value 'IRWO' ##NO_TEXT.
  constants C_KEY_IRR_PO type ZABS_DEL_K1VAL value 'IRPO' ##NO_TEXT.
  constants C_ITEM_CAT_L type POSTP value 'L' ##NO_TEXT.
  constants C_STND_MSG_CLASS type MSGID value '/AGRI/FMWO' ##NO_TEXT.
  constants C_WOTYP_ZWOM type /AGRI/FMWOTYP value 'ZWOM' ##NO_TEXT.
  constants C_VERID_0001 type VERID value '0001' ##NO_TEXT.
  constants C_WO_SPLAPPL_1 type /AGRI/GLSAPPL value '1' ##NO_TEXT.
  constants C_STR_QUAL_CHAR type DD02L-TABNAME value 'ZABS_STR_QUAL_CHAR' ##NO_TEXT.
  constants C_STR_HCM_EMPREC type DD02L-TABNAME value 'ZABS_STR_EMPREC' ##NO_TEXT.
  constants C_UCOMM_BACK type SYST_UCOMM value 'BACK' ##NO_TEXT.
  constants C_RSTYP_LABOUR type /AGRI/FMRSTYPE value 'A' ##NO_TEXT.
  constants C_OBJID_HCM_WRKC type ZABS_DEL_OBJID value 'HCM' ##NO_TEXT.
  constants C_KEY_WORK_CENTER type CHAR4 value 'WRKC' ##NO_TEXT.
  constants C_HCM_EMP_SUBGRP type PERSK value 'SB' ##NO_TEXT.
  constants C_STR_HCM_CLASSREC type DD02L-TABNAME value 'ZABS_STR_CLASSREC' ##NO_TEXT.
  constants C_ICON_GO type ZABS_DEL_MSGTYP value '@5B@' ##NO_TEXT.
  constants C_ICON_STOP type ZABS_DEL_MSGTYP value '@5C@' ##NO_TEXT.
  constants C_TURMA_COLHEITA type ZFMTURMA_TIPO value 'ZCLH' ##NO_TEXT.
  constants C_TURSTAT_ACTIVE type ZFM_STATUS value '01' ##NO_TEXT.
  constants C_EMP_STATUS type STAT2 value '3' ##NO_TEXT.
  constants C_UOM type CO_ISMNGEH value 'M3' ##NO_TEXT.
  constants C_MEINH_HAR type VORME value 'HAR' ##NO_TEXT.
  constants C_ARBPL_AGUA type ARBPL value 'AGUA' ##NO_TEXT.
  constants C_DRPDOWN_HANDLE1 type INT4 value '1' ##NO_TEXT.
  constants C_VARIANT_HNDL_ITEM type SLIS_HANDL value 'ITEM' ##NO_TEXT.
  constants C_STR_IRR_CNF type DD02L-TABNAME value 'ZABS_STR_OCNF' ##NO_TEXT.
  constants C_STR_IRR_CON type DD02L-TABNAME value 'ZABS_STR_OCON' ##NO_TEXT.
  constants C_ORDCNF_UMREN type CP_UMREN value '1' ##NO_TEXT.
  constants C_F4_VALORG_S type DDBOOL_D value 'S' ##NO_TEXT.
  constants C_PO_PCNF type /AGRI/FMCSTAT value 'PCNF' ##NO_TEXT.
  constants C_OBJ_FMOC type INRI-OBJECT value '/AGRI/FMOC' ##NO_TEXT.
  constants C_REP_WO_CNF type REPID value 'ZABS_REP_WO_CONF' ##NO_TEXT.
  constants C_ROPT_BETWEEN type CHAR2 value 'BT' ##NO_TEXT.
  constants C_KEY_IRR_MNTH type ZABS_DEL_K1VAL value 'MNTH' ##NO_TEXT.
  constants C_IRRTYP_001 type /AGRI/FMIRTYP value '001' ##NO_TEXT.
  constants C_IRRTYP_002 type /AGRI/FMIRTYP value '002' ##NO_TEXT.
  constants C_IRRTYP_003 type /AGRI/FMIRTYP value '003' ##NO_TEXT.
  constants C_CLASS_EVAP type /AGRI/GATGRP value 'EVAPORATION' ##NO_TEXT.
  constants C_CLASS_PREC type /AGRI/GATGRP value 'PRECIPITACION' ##NO_TEXT.
  constants C_CLASS_INFO type /AGRI/GATGRP value 'INFO_PROJETO' ##NO_TEXT.
  constants C_CHARACT_COEF type ATNAM value 'COEF_CULTURA' ##NO_TEXT.
  constants C_CLASS_TENSIO type /AGRI/GATGRP value 'TENSIOMETRIA' ##NO_TEXT.
  constants C_CHARACT_TENSIO type ATNAM value 'TENSAO_SOLO' ##NO_TEXT.
  constants C_IRRFLAG_HYDRIC type ZABS_DEL_ATYP value 'H' ##NO_TEXT.
  constants C_IRRFLAG_TENSIO type ZABS_DEL_ATYP value 'T' ##NO_TEXT.
  constants C_IRRFLAG_FIELD_CAP type ZABS_DEL_ATYP value 'F' ##NO_TEXT.
  constants C_KEY_IRR_DAYS type ZABS_DEL_K1VAL value 'DAYS' ##NO_TEXT.
  constants C_KEY_IRR_VNPER type ZABS_DEL_K1VAL value 'VNPER' ##NO_TEXT.
  constants C_IRR_INFO_FCAT type DD02L-TABNAME value 'ZABS_STR_IRRORD_INFO' ##NO_TEXT.
  constants C_CLASS_NIRR_RSN type /AGRI/GATGRP value 'MOTIVO_NAO_IRRIGAÇ' ##NO_TEXT.
  constants C_CHARACT_NIRSN_SFT1 type ATNAM value 'SHIFT1_NAOIRRIGA' ##NO_TEXT.
  constants C_CHARACT_NIRSN_SFT2 type ATNAM value 'SHIFT2_NAOIRRIGA' ##NO_TEXT.
  constants C_CHARACT_NIRSN_SFT3 type ATNAM value 'SHIFT3_NAOIRRIGA' ##NO_TEXT.
  constants C_CHARACT_NIRSN_SFT4 type ATNAM value 'SHIFT4_NAOIRRIGA' ##NO_TEXT.
  constants C_CHARACT_NIRSN_SFT5 type ATNAM value 'SHIFT5_NAOIRRIGA' ##NO_TEXT.
  constants C_CHARACT_NIRSN_SFT6 type ATNAM value 'SHIFT6_NAOIRRIGA' ##NO_TEXT.
  constants C_TMATNR_FORD type /AGRI/GLTMATNR value 'TFOR0350' ##NO_TEXT.
  constants C_DCLASS_OWPR type /AGRI/GLGTART value 'OWPR' ##NO_TEXT.
  constants C_DCLASS_STATUS type /AGRI/GLELOEK value 'S' ##NO_TEXT.
  constants C_KEY_MOB_WBDAYS type ZABS_DEL_K1VAL value 'WBDAYS' ##NO_TEXT.
  constants C_GIS_SYSTEM type ZABS_DEL_SYSTEM value 'GIS' ##NO_TEXT.
  constants C_ROLE_EQUIP type CHAR2 value 'EQ' ##NO_TEXT.
  constants C_CHARACT_CIT type ATNAM value 'CIT-ESPACAMENTO-RUA' ##NO_TEXT.
  constants C_CLASS_FAZPLANTIO type /AGRI/GATGRP value 'FAZ-PLANTIO' ##NO_TEXT.
  constants C_MDTYP_ZPTA type /AGRI/GLMDTYP value 'ZPTA' ##NO_TEXT.
  constants C_DOMAIN_UROLE type DD01L-DOMNAME value 'ZABS_DOM_UROLE' ##NO_TEXT.
  constants C_DOMAIN_PEVT type DD01L-DOMNAME value 'ZABS_DOM_PEVT' ##NO_TEXT.
  constants C_DOMAIN_FPCNF type DD01L-DOMNAME value 'ZABS_DOM_FPCNF' ##NO_TEXT.
  constants C_ACTCG_MACHINERY type ZABS_DEL_ACTCG value 'M' ##NO_TEXT.
  constants C_ACCTYP_TAST type /AGRI/FMACTYP value 'TAST' ##NO_TEXT.
  constants C_KEY_MCH_DAYS type ZABS_DEL_K1VAL value 'DAYS' ##NO_TEXT.
  constants C_KEY_MCH_ACT type ZABS_DEL_K1VAL value 'ACT' ##NO_TEXT.
  constants C_OBJID_MCH type ZABS_DEL_OBJID value 'MCH' ##NO_TEXT.
  constants C_KEY_MCH_GTOL type ZABS_DEL_K1VAL value 'GTOL' ##NO_TEXT.
  constants C_AC_STATUS_DELETED type /AGRI/FMAC_STATUS value 'DEL' ##NO_TEXT.
  constants C_KEY_LGSTRP type ZABS_DEL_K1VAL value 'LGSTRP' ##NO_TEXT.
  constants C_KEY_HGSTRP type ZABS_DEL_K1VAL value 'HGSTRP' ##NO_TEXT.
  constants C_ACCTYP_TAS2 type /AGRI/FMACTYP value 'TAS2' ##NO_TEXT.
  constants C_TOCNF_MLOG_FCAT type DD02L-TABNAME value 'ZABS_STR_TOCNF_MLOG' ##NO_TEXT.
  constants C_JOB_BATCH type SYST_BATCH value 'B' ##NO_TEXT.
  constants C_ACCTYP_TAS3 type /AGRI/FMACTYP value 'TAS3' ##NO_TEXT.
  constants C_ACC_RSTYP_EQUIP type /AGRI/FMACRSTYP value 'EQ' ##NO_TEXT.
  constants C_STATUS_CREATE type ZABS_DEL_STATUS value 'C' ##NO_TEXT.
  constants C_STATUS_ERROR type ZABS_DEL_STATUS value 'E' ##NO_TEXT.
  constants C_STATUS_PROCESS type ZABS_DEL_STATUS value 'P' ##NO_TEXT.
  constants C_STATUS_REPROCESS type ZABS_DEL_STATUS value 'R' ##NO_TEXT.
  constants C_OBJID_MOBL type ZABS_DEL_OBJID value 'MOBL' ##NO_TEXT.
  constants C_KEY_GIRR type ZABS_DEL_K1VAL value 'GIRR' ##NO_TEXT.
  constants C_KEY_DIND type ZABS_DEL_K2VAL value 'DIND' ##NO_TEXT.
  constants C_MSG_CLASS_/AGRI/FMFP type MSGID value '/AGRI/FMFP' ##NO_TEXT.
  constants C_MSG_NO_51 type MSGNO value '051' ##NO_TEXT.
  constants C_ACTCG_NON_PRODUCTIVE type ZABS_DEL_ACTCG value 'N' ##NO_TEXT.
  constants C_UROLE_01 type ZABS_DEL_UROLE value '01' ##NO_TEXT.
  constants C_UROLE_04 type ZABS_DEL_UROLE value '04' ##NO_TEXT.
  constants C_KEY_NPRO type ZABS_DEL_K1VAL value 'NPRO' ##NO_TEXT.
  constants C_KEY_INSPOP type ZABS_DEL_K1VAL value 'INSPOP' ##NO_TEXT.
  constants C_KEY_13 type ZABS_DEL_K3VAL value '13' ##NO_TEXT.
  constants C_KEY_VHDAYS type ZABS_DEL_K2VAL value 'VHDAYS' ##NO_TEXT.
  constants C_KEY_VLDAYS type ZABS_DEL_K2VAL value 'VLDAYS' ##NO_TEXT.
  constants C_KEY_NUR type ZABS_DEL_K1VAL value 'NUR' ##NO_TEXT.
  constants C_KEY_AUDIT type ZABS_DEL_K2VAL value 'AUDIT' ##NO_TEXT.
protected section.
private section.
ENDCLASS.



CLASS ZCL_ABS_ABAP_MAINTAIN IMPLEMENTATION.
ENDCLASS.
